name: ease-dev
channels:
- defaults
dependencies:
- cycler=0.10.0=py36_0
- dbus=1.10.20=0
- decorator=4.1.2=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_2
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_0
- path.py=10.3.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.34=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.1.3=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=5
- readline=6.2=2
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xarray=0.9.6=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - aiohttp==2.2.3
  - alabaster==0.7.10
  - archapp (/reg/neh/home4/nwbrown/Documents/archapp/lib)==0.0.0
  - async-timeout==1.2.1
  - babel==2.4.0
  - certifi==2017.7.27.1
  - chardet==3.0.4
  - django==1.11.3
  - docutils==0.13.1
  - gunicorn==19.7.1
  - idna==2.5
  - imagesize==0.7.1
  - ipython-genutils==0.2.0
  - jinja2==2.9.6
  - markupsafe==1.0
  - multidict==3.1.3
  - prompt-toolkit==1.0.14
  - requests==2.18.2
  - selenium==3.6.0
  - snowballstemmer==1.2.1
  - sphinx==1.6.3
  - sphinxcontrib-websupport==1.0.1
  - urllib3==1.22
  - whitenoise==3.3.0
  - yarl==0.12.0

